#[allow(dead_code)]
pub mod prompt_deliver;

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::anyhow;

use crate::Result;
use crate::cli::HooksInstallArgs;

const OMC_HOOK_PREFIX: &str = "clawhip-";
const OMX_HOOK_NAME: &str = "clawhip.mjs";
const OMX_SDK_NAME: &str = "clawhip-sdk.mjs";
const HOOKS_TOML_NAME: &str = "hooks.toml";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InstallReport {
    pub omc_files: Vec<PathBuf>,
    pub omx_files: Vec<PathBuf>,
    pub config_path: Option<PathBuf>,
}

pub fn install(args: HooksInstallArgs) -> Result<()> {
    let targets = resolve_targets(&args)?;
    let report = run_install(&targets, &args)?;

    if !report.omc_files.is_empty() {
        println!("Installed OMC hooks to {}:", targets.omc_dir.display());
        for path in &report.omc_files {
            println!("  {}", path.display());
        }
    }

    if !report.omx_files.is_empty() {
        println!("Installed OMX hooks to {}:", targets.omx_dir.display());
        for path in &report.omx_files {
            println!("  {}", path.display());
        }
    }

    if let Some(config_path) = &report.config_path {
        println!("Generated config: {}", config_path.display());
    }

    if report.omc_files.is_empty() && report.omx_files.is_empty() {
        println!("Nothing installed. Use --omc, --omx, or --all to select targets.");
    }

    Ok(())
}

struct InstallTargets {
    install_omc: bool,
    install_omx: bool,
    omc_dir: PathBuf,
    omx_dir: PathBuf,
    config_dir: PathBuf,
}

fn resolve_targets(args: &HooksInstallArgs) -> Result<InstallTargets> {
    let install_omc = args.all || args.omc;
    let install_omx = args.all || args.omx;

    let home = home_dir()?;

    let omc_dir = args
        .omc_dir
        .clone()
        .unwrap_or_else(|| home.join(".claude").join("hooks"));

    let omx_dir = args
        .omx_dir
        .clone()
        .unwrap_or_else(|| PathBuf::from(".omx").join("hooks"));

    let config_dir = home.join(".clawhip");

    Ok(InstallTargets {
        install_omc,
        install_omx,
        omc_dir,
        omx_dir,
        config_dir,
    })
}

fn run_install(targets: &InstallTargets, _args: &HooksInstallArgs) -> Result<InstallReport> {
    let mut report = InstallReport {
        omc_files: Vec::new(),
        omx_files: Vec::new(),
        config_path: None,
    };

    if targets.install_omc {
        report.omc_files = install_omc_hooks(&targets.omc_dir)?;
    }

    if targets.install_omx {
        report.omx_files = install_omx_hooks(&targets.omx_dir)?;
    }

    if targets.install_omc || targets.install_omx {
        report.config_path = Some(generate_hooks_config(&targets.config_dir)?);
    }

    Ok(report)
}

fn install_omc_hooks(dest: &Path) -> Result<Vec<PathBuf>> {
    fs::create_dir_all(dest)?;

    let hooks = [
        (
            format!("{OMC_HOOK_PREFIX}session-init.sh"),
            omc_session_init_hook(),
        ),
        (
            format!("{OMC_HOOK_PREFIX}session-stop.sh"),
            omc_session_stop_hook(),
        ),
    ];

    let mut installed = Vec::new();
    for (name, content) in &hooks {
        let path = dest.join(name);
        fs::write(&path, content)?;
        #[cfg(unix)]
        set_executable(&path)?;
        installed.push(path);
    }

    Ok(installed)
}

fn install_omx_hooks(dest: &Path) -> Result<Vec<PathBuf>> {
    fs::create_dir_all(dest)?;

    let source_dir = bundled_omx_integrations_dir();
    let mut installed = Vec::new();

    let hook_path = dest.join(OMX_HOOK_NAME);
    if source_dir.join("clawhip-hook.mjs").is_file() {
        fs::copy(source_dir.join("clawhip-hook.mjs"), &hook_path)?;
    } else {
        fs::write(&hook_path, omx_hook_fallback())?;
    }
    installed.push(hook_path);

    let lib_dir = dest.join("lib");
    fs::create_dir_all(&lib_dir)?;
    let sdk_path = lib_dir.join(OMX_SDK_NAME);
    if source_dir.join("clawhip-sdk.mjs").is_file() {
        fs::copy(source_dir.join("clawhip-sdk.mjs"), &sdk_path)?;
    } else {
        fs::write(&sdk_path, omx_sdk_fallback())?;
    }
    installed.push(sdk_path);

    Ok(installed)
}

fn generate_hooks_config(config_dir: &Path) -> Result<PathBuf> {
    fs::create_dir_all(config_dir)?;
    let config_path = config_dir.join(HOOKS_TOML_NAME);

    if config_path.exists() {
        return Ok(config_path);
    }

    fs::write(&config_path, default_hooks_toml())?;
    Ok(config_path)
}

fn default_hooks_toml() -> &'static str {
    r#"# clawhip hooks configuration
# Generated by `clawhip hooks install`

[hooks]
enabled = ["session-init", "session-stop"]

[hooks.session-idle]
threshold_minutes = 30

[discord]
bidirectional = false
"#
}

fn omc_session_init_hook() -> &'static str {
    r#"#!/usr/bin/env bash
# clawhip OMC session-init hook
# Emits session.started to the clawhip daemon
set -euo pipefail

CLAWHIP="${CLAWHIP_BIN:-clawhip}"

if ! command -v "$CLAWHIP" &>/dev/null; then
    exit 0
fi

SESSION_ID="${CLAUDE_SESSION_ID:-unknown}"
PROJECT="$(basename "${PWD}")"

"$CLAWHIP" emit session.started \
    --agent omc \
    --session "$SESSION_ID" \
    --project "$PROJECT" 2>/dev/null || true
"#
}

fn omc_session_stop_hook() -> &'static str {
    r#"#!/usr/bin/env bash
# clawhip OMC session-stop hook
# Emits session.finished to the clawhip daemon
set -euo pipefail

CLAWHIP="${CLAWHIP_BIN:-clawhip}"

if ! command -v "$CLAWHIP" &>/dev/null; then
    exit 0
fi

SESSION_ID="${CLAUDE_SESSION_ID:-unknown}"
PROJECT="$(basename "${PWD}")"

"$CLAWHIP" emit session.finished \
    --agent omc \
    --session "$SESSION_ID" \
    --project "$PROJECT" 2>/dev/null || true
"#
}

fn omx_hook_fallback() -> &'static str {
    r#"import { createClawhipOmxClient } from './lib/clawhip-sdk.mjs';

const clientPromise = createClawhipOmxClient();

export async function onHookEvent(event, sdk) {
  const client = await clientPromise;
  const result = await client.emitFromHookEvent(event, {
    context: { agent_name: 'omx' },
  });
  return result;
}
"#
}

fn omx_sdk_fallback() -> &'static str {
    r#"// clawhip OMX SDK — fallback stub
// Install the full SDK with: clawhip hooks install --omx
export function createClawhipOmxClient() {
  const baseUrl = process.env.CLAWHIP_BASE_URL || 'http://127.0.0.1:3838';
  return {
    async emitFromHookEvent(event, opts) {
      try {
        const resp = await fetch(`${baseUrl}/api/omx/hook`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...event, ...opts }),
        });
        return await resp.json();
      } catch { return { skipped: true, reason: 'clawhip unreachable' }; }
    },
  };
}
"#
}

fn bundled_omx_integrations_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("integrations")
        .join("omx")
}

fn home_dir() -> Result<PathBuf> {
    env::var("HOME")
        .map(PathBuf::from)
        .map_err(|_| anyhow!("HOME environment variable not set").into())
}

#[cfg(unix)]
fn set_executable(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = fs::metadata(path)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(path, perms)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_install_targets(dir: &Path) -> InstallTargets {
        InstallTargets {
            install_omc: true,
            install_omx: true,
            omc_dir: dir.join("claude-hooks"),
            omx_dir: dir.join("omx-hooks"),
            config_dir: dir.join("clawhip-config"),
        }
    }

    #[test]
    fn install_omc_hooks_creates_shell_scripts() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let dest = tempdir.path().join("claude-hooks");

        let installed = install_omc_hooks(&dest).expect("install omc hooks");

        assert_eq!(installed.len(), 2);
        assert!(dest.join("clawhip-session-init.sh").is_file());
        assert!(dest.join("clawhip-session-stop.sh").is_file());

        let content = fs::read_to_string(dest.join("clawhip-session-init.sh")).unwrap();
        assert!(content.contains("session.started"));
        assert!(content.contains("#!/usr/bin/env bash"));
    }

    #[test]
    fn install_omx_hooks_creates_mjs_files() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let dest = tempdir.path().join("omx-hooks");

        let installed = install_omx_hooks(&dest).expect("install omx hooks");

        assert_eq!(installed.len(), 2);
        assert!(dest.join("clawhip.mjs").is_file());
        assert!(dest.join("lib").join("clawhip-sdk.mjs").is_file());
    }

    #[test]
    fn generate_hooks_config_creates_toml() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let config_dir = tempdir.path().join("clawhip-config");

        let path = generate_hooks_config(&config_dir).expect("generate config");

        assert_eq!(path, config_dir.join("hooks.toml"));
        assert!(path.is_file());

        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("[hooks]"));
        assert!(content.contains("session-init"));
        assert!(content.contains("bidirectional = false"));
    }

    #[test]
    fn generate_hooks_config_preserves_existing() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let config_dir = tempdir.path().join("clawhip-config");
        fs::create_dir_all(&config_dir).unwrap();

        let config_path = config_dir.join("hooks.toml");
        fs::write(&config_path, "# custom config\n").unwrap();

        let path = generate_hooks_config(&config_dir).expect("generate config");

        let content = fs::read_to_string(&path).unwrap();
        assert_eq!(content, "# custom config\n");
    }

    #[test]
    fn run_install_installs_both_targets() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let targets = temp_install_targets(tempdir.path());
        let args = HooksInstallArgs {
            omc: true,
            omx: true,
            all: false,
            omc_dir: None,
            omx_dir: None,
        };

        let report = run_install(&targets, &args).expect("run install");

        assert!(!report.omc_files.is_empty());
        assert!(!report.omx_files.is_empty());
        assert!(report.config_path.is_some());
    }

    #[test]
    fn resolve_targets_defaults_without_flags() {
        let args = HooksInstallArgs {
            omc: false,
            omx: false,
            all: false,
            omc_dir: None,
            omx_dir: None,
        };

        let targets = resolve_targets(&args).expect("resolve targets");
        assert!(!targets.install_omc);
        assert!(!targets.install_omx);
    }

    #[test]
    fn resolve_targets_all_enables_both() {
        let args = HooksInstallArgs {
            omc: false,
            omx: false,
            all: true,
            omc_dir: None,
            omx_dir: None,
        };

        let targets = resolve_targets(&args).expect("resolve targets");
        assert!(targets.install_omc);
        assert!(targets.install_omx);
    }
}
